### ISSUE TITLE
username column not found

### ISSUE THREAD

**Issue by adlytodak** [Lysice/laravel-sso#1]
using manual auth laravel, only send email to auth and google sign in. how to solve this?

**Comment by Lysice** [comment]
You can use multi mode.
And this feature is not specified in the document, just for my working.
Later I'll add this. Please wait for a while.

**Comment by adlytodak** [comment]
thank you. im looking foward to hear from you.

**Comment by Lysice** [comment]
@adlytodak 
Now doc is finished.whatever the bug happens add issues.
Thanks for using it!
